const teamLogoMap: Record<string, string> = {
  'Club Brugge': '/teams/club-brugge.png',
  'Anderlecht': '/teams/anderlecht.png',
  'Union': '/teams/union.png',
  'KRC Genk': '/teams/genk.png',
  'KAA Gent': '/teams/gent.png',
  'Standard': '/teams/standard.png',
  'Antwerp': '/teams/antwerp.png',
  'STVV': '/teams/stvv.png',
  'KV Mechelen': '/teams/mechelen.png',
  'Westerlo': '/teams/westerlo.png',
  'Charleroi': '/teams/charleroi.png',
  'OH Leuven': '/teams/oh-leuven.png',
  'Cercle Brugge': '/teams/cercle-brugge.png',
  'Zulte Waregem': '/teams/zulte-waregem.png',
  'Dender': '/teams/dender.png',
  'RAAL La Louvière': '/teams/raal-la-louviere.png',
  'SK Beveren': '/teams/sk-beveren.png',
  'KV Kortrijk': '/teams/kv-kortrijk.png',
  'Beerschot': '/teams/beerschot.png',
  'Patro Eisden': '/teams/patro-eisden.png',
  'Lommel SK': '/teams/lommel-sk.png',
  'Eupen': '/teams/eupen.png',
  'Lierse': '/teams/lierse.png',
  'Lokeren': '/teams/lokeren.png',
  'KV Oostende': '/teams/kv-oostende.png',
  'RWDM': '/teams/rwdm.png',
  'Aalst': '/teams/aalst.png',
  // Aliases for DB team names that differ
  'Gent': '/teams/gent.png',
  'Mechelen': '/teams/mechelen.png',
  'Genk': '/teams/genk.png',
}

export const FAVORITE_TEAMS = [
  'Club Brugge',
  'Anderlecht',
  'Union',
  'KRC Genk',
  'KAA Gent',
  'Standard',
  'Antwerp',
  'STVV',
  'KV Mechelen',
  'Westerlo',
  'Charleroi',
  'OH Leuven',
  'Cercle Brugge',
  'Zulte Waregem',
  'Dender',
  'RAAL La Louvière',
  'SK Beveren',
  'KV Kortrijk',
  'Beerschot',
  'Patro Eisden',
  'Lommel SK',
  'Eupen',
  'Lierse',
  'Lokeren',
  'KV Oostende',
  'RWDM',
  'Aalst',
]

export function getTeamLogo(teamName: string): string | null {
  return teamLogoMap[teamName] ?? null
}
